// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:993820037887:web:cd66c82f3f07e0c44272ca',
    messagingSenderId: '993820037887',
    projectId: 'isro-42cd3',
    authDomain: 'isro-42cd3.firebaseapp.com',
    storageBucket: 'isro-42cd3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHwAtSaMzXADdJ6IOaK8dS2TkQXeYBD6o',
    appId: '1:993820037887:android:cd66c82f3f07e0c44272ca',
    messagingSenderId: '993820037887',
    projectId: 'isro-42cd3',
    authDomain: 'isro-42cd3.firebaseapp.com',
    storageBucket: 'isro-42cd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHwAtSaMzXADdJ6IOaK8dS2TkQXeYBD6o',
    appId: '1:993820037887:ios:cd66c82f3f07e0c44272ca',
    messagingSenderId: '993820037887',
    projectId: 'isro-42cd3',
    authDomain: 'isro-42cd3.firebaseapp.com',
    storageBucket: 'isro-42cd3.firebasestorage.app',
    iosBundleId: 'com.example.isroQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHwAtSaMzXADdJ6IOaK8dS2TkQXeYBD6o',
    appId: '1:993820037887:macos:cd66c82f3f07e0c44272ca',
    messagingSenderId: '993820037887',
    projectId: 'isro-42cd3',
    authDomain: 'isro-42cd3.firebaseapp.com',
    storageBucket: 'isro-42cd3.firebasestorage.app',
    iosBundleId: 'com.example.isroQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHwAtSaMzXADdJ6IOaK8dS2TkQXeYBD6o',
    appId: '1:993820037887:web:cd66c82f3f07e0c44272ca',
    messagingSenderId: '993820037887',
    projectId: 'isro-42cd3',
    authDomain: 'isro-42cd3.firebaseapp.com',
    storageBucket: 'isro-42cd3.firebasestorage.app',
  );
}
